# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tracker_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tracker_config.proto',
  package='linktracker',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14tracker_config.proto\x12\x0blinktracker\"\xd0\x05\n\rTrackerConfig\x12\"\n\x1anorthbound_station_stop_id\x18\x01 \x01(\t\x12\"\n\x1asouthbound_station_stop_id\x18\x02 \x01(\t\x12\'\n\x1f\x64\x65pature_fetch_interval_seconds\x18\x04 \x01(\x05\x12@\n\x0e\x64isplay_config\x18\x03 \x01(\x0b\x32(.linktracker.TrackerConfig.DisplayConfig\x1a\x8b\x04\n\rDisplayConfig\x12\"\n\x1a\x64\x61ytime_display_brightness\x18\x01 \x01(\x02\x12$\n\x1cnighttime_display_brightness\x18\x02 \x01(\x02\x12\x1c\n\x14\x64isplay_width_pixels\x18\x03 \x01(\x05\x12\x1d\n\x15\x64isplay_height_pixels\x18\x04 \x01(\x05\x12\x15\n\rgpio_slowdown\x18\x05 \x01(\x05\x12\'\n\x0btitle_color\x18\x06 \x01(\x0b\x32\x12.linktracker.Color\x12-\n\x11north_label_color\x18\x07 \x01(\x0b\x32\x12.linktracker.Color\x12-\n\x11south_label_color\x18\x08 \x01(\x0b\x32\x12.linktracker.Color\x12\x30\n\x14predicted_time_color\x18\t \x01(\x0b\x32\x12.linktracker.Color\x12\x30\n\x14scheduled_time_color\x18\n \x01(\x0b\x32\x12.linktracker.Color\x12-\n\x11no_arrivals_color\x18\x0b \x01(\x0b\x32\x12.linktracker.Color\x12\x11\n\tpaint_fps\x18\x0c \x01(\x02\x12/\n\'recalculate_brightness_interval_seconds\x18\r \x01(\x05\"(\n\x05\x43olor\x12\t\n\x01r\x18\x01 \x01(\x05\x12\t\n\x01g\x18\x02 \x01(\x05\x12\t\n\x01\x62\x18\x03 \x01(\x05\x62\x06proto3'
)




_TRACKERCONFIG_DISPLAYCONFIG = _descriptor.Descriptor(
  name='DisplayConfig',
  full_name='linktracker.TrackerConfig.DisplayConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='daytime_display_brightness', full_name='linktracker.TrackerConfig.DisplayConfig.daytime_display_brightness', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nighttime_display_brightness', full_name='linktracker.TrackerConfig.DisplayConfig.nighttime_display_brightness', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='display_width_pixels', full_name='linktracker.TrackerConfig.DisplayConfig.display_width_pixels', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='display_height_pixels', full_name='linktracker.TrackerConfig.DisplayConfig.display_height_pixels', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gpio_slowdown', full_name='linktracker.TrackerConfig.DisplayConfig.gpio_slowdown', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title_color', full_name='linktracker.TrackerConfig.DisplayConfig.title_color', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='north_label_color', full_name='linktracker.TrackerConfig.DisplayConfig.north_label_color', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='south_label_color', full_name='linktracker.TrackerConfig.DisplayConfig.south_label_color', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='predicted_time_color', full_name='linktracker.TrackerConfig.DisplayConfig.predicted_time_color', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='scheduled_time_color', full_name='linktracker.TrackerConfig.DisplayConfig.scheduled_time_color', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='no_arrivals_color', full_name='linktracker.TrackerConfig.DisplayConfig.no_arrivals_color', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='paint_fps', full_name='linktracker.TrackerConfig.DisplayConfig.paint_fps', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='recalculate_brightness_interval_seconds', full_name='linktracker.TrackerConfig.DisplayConfig.recalculate_brightness_interval_seconds', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=235,
  serialized_end=758,
)

_TRACKERCONFIG = _descriptor.Descriptor(
  name='TrackerConfig',
  full_name='linktracker.TrackerConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='northbound_station_stop_id', full_name='linktracker.TrackerConfig.northbound_station_stop_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='southbound_station_stop_id', full_name='linktracker.TrackerConfig.southbound_station_stop_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='depature_fetch_interval_seconds', full_name='linktracker.TrackerConfig.depature_fetch_interval_seconds', index=2,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='display_config', full_name='linktracker.TrackerConfig.display_config', index=3,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_TRACKERCONFIG_DISPLAYCONFIG, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=758,
)


_COLOR = _descriptor.Descriptor(
  name='Color',
  full_name='linktracker.Color',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='r', full_name='linktracker.Color.r', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='g', full_name='linktracker.Color.g', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='b', full_name='linktracker.Color.b', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=760,
  serialized_end=800,
)

_TRACKERCONFIG_DISPLAYCONFIG.fields_by_name['title_color'].message_type = _COLOR
_TRACKERCONFIG_DISPLAYCONFIG.fields_by_name['north_label_color'].message_type = _COLOR
_TRACKERCONFIG_DISPLAYCONFIG.fields_by_name['south_label_color'].message_type = _COLOR
_TRACKERCONFIG_DISPLAYCONFIG.fields_by_name['predicted_time_color'].message_type = _COLOR
_TRACKERCONFIG_DISPLAYCONFIG.fields_by_name['scheduled_time_color'].message_type = _COLOR
_TRACKERCONFIG_DISPLAYCONFIG.fields_by_name['no_arrivals_color'].message_type = _COLOR
_TRACKERCONFIG_DISPLAYCONFIG.containing_type = _TRACKERCONFIG
_TRACKERCONFIG.fields_by_name['display_config'].message_type = _TRACKERCONFIG_DISPLAYCONFIG
DESCRIPTOR.message_types_by_name['TrackerConfig'] = _TRACKERCONFIG
DESCRIPTOR.message_types_by_name['Color'] = _COLOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TrackerConfig = _reflection.GeneratedProtocolMessageType('TrackerConfig', (_message.Message,), {

  'DisplayConfig' : _reflection.GeneratedProtocolMessageType('DisplayConfig', (_message.Message,), {
    'DESCRIPTOR' : _TRACKERCONFIG_DISPLAYCONFIG,
    '__module__' : 'tracker_config_pb2'
    # @@protoc_insertion_point(class_scope:linktracker.TrackerConfig.DisplayConfig)
    })
  ,
  'DESCRIPTOR' : _TRACKERCONFIG,
  '__module__' : 'tracker_config_pb2'
  # @@protoc_insertion_point(class_scope:linktracker.TrackerConfig)
  })
_sym_db.RegisterMessage(TrackerConfig)
_sym_db.RegisterMessage(TrackerConfig.DisplayConfig)

Color = _reflection.GeneratedProtocolMessageType('Color', (_message.Message,), {
  'DESCRIPTOR' : _COLOR,
  '__module__' : 'tracker_config_pb2'
  # @@protoc_insertion_point(class_scope:linktracker.Color)
  })
_sym_db.RegisterMessage(Color)


# @@protoc_insertion_point(module_scope)
